### ISSUE TITLE
Limit the amount of players 

### ISSUE THREAD

**Issue by NightfoxGames** [RiptideNetworking/Riptide#106]
Hey, i find it really cool what you created and im making my dream game with it! but is there any way you can limit the amount of players in one lobby?

**Comment by Techyte** [comment]
In the server class there is a field called `MaxClientCount`. You can also set it in the server start function, something like this; `Server.Start(port, maxClientCount);`. Just replace maxClientCount with whatever you want to limit your number of players too

Is that what your looking for?

**Comment by tom-weiland** [comment]
As @Techyte said, you can set the max client amount when calling `Server.Start`.

**Comment by NightfoxGames** [comment]
Thanks a lot! This is really what is have been looking for, now I just need a character selector and I’m done with the basics!
