### ISSUE TITLE
Character Selection Info

### ISSUE THREAD

**Issue by NightfoxGames** [RiptideNetworking/Riptide#107]
Hey, I want to create a character select menu for my game and have the idea set up, But I have no idea if it's even possible since you have 1 player prefab. Is there any side effect to changing the 1 "normal" player prefab to an array of multiple?

**Comment by tom-weiland** [comment]
> Is there any side effect to changing the 1 "normal" player prefab to an array of multiple?

No, that's not directly Riptide- or networking-related, so the only side effects you'll experience are those you cause yourself, such as forgetting to ensure the same prefab is spawned on all clients or not including the necessary networking stuff on all prefabs.

If you have any other questions of this nature, please [join the Discord server](https://discord.gg/tomweiland) and ask there, and reserve GitHub issues for when you actually run into an issue with the library itself (not your own code).
