### ISSUE TITLE
Weird Timeout

### ISSUE THREAD

**Issue by JingchengYang4** [RiptideNetworking/Riptide#115]
I'm implementing a server meshing system so that multiple instances of Riptide server is running on a dotnet program. I don't think it's related but, I'm indeed getting weird timeouts and delivery fail warnings.

<img width="868" alt="截屏2023-09-09 下午6 08 05" src="https://github.com/RiptideNetworking/Riptide/assets/43139384/373b7d8c-6431-48ae-9e77-e8fd89a534e7">

I feel like a simpler explanation would be the fact that when I focus on one instance (perhaps the editor), the other stop running in the background and be deemed as "timeout". It does seem that having Connection.CanTimeOut = false resolves the issue. 

It does seem like having a buffer system might be useful, in the case that reliable messages cannot be sent, they stack up somewhere and be sent once the heartbeat is reestablished. I've noticed if a game sits in the background while a player is spawned, this does not get spawned after the game has resumed foreground and reestablished connections. This might be useful for situations where a network lag / outage for a couple of seconds to half a minute occurs.

**Comment by tom-weiland** [comment]
Do you have the Run in Background option enabled in your project(s)? Without it, your servers/clients will effectively freeze unless they're the focused window, which will cause them to time out.

**Comment by JingchengYang4** [comment]
Alright, thanks for the confirmation. Also, just to ask, no part of the library utilizes Task or any multithreaded code? I don't want it to conflict with my meshing implementation.

**Comment by tom-weiland** [comment]
There was some multi-threaded stuff prior to v2.0.0, but since v2 everything is single-threaded and *not* thread safe.

**Comment by JingchengYang4** [comment]
For now I haven't seen any issues. So it is working, thank you.
