### ISSUE TITLE
Nuget packages

### ISSUE THREAD

**Issue by IrishBruse** [RiptideNetworking/Riptide#12]
I use Monogame framework and this networking solution works with it. I was wondering for the pure c# stuff you could release the network solution as a nuget package. Would make adding it to console apps and monogame apps alot easier.

**Comment by ERmilburn02** [comment]
I think this would be a good idea

**Comment by IrishBruse** [comment]
Also making it support net5.0 and net6.0 too

**Comment by ERmilburn02** [comment]
it's .Net Standard, it should work with .Net 5 and 6. It's working fine in my .Net 6 projects

**Comment by IrishBruse** [comment]
Yeah its better for the dll to be compiled with dotnet 5 and 6 and if its in a nuget package its no more difficult than adding in the .csproj
```
<TargetFramework>netcoreapp3.1</TargetFramework>
<TargetFrameworks>netcoreapp3.1;net5.0;net6.0</TargetFrameworks>
```

**Comment by BlackOfWorld** [comment]
> Yeah its better for the dll to be compiled with dotnet 5 and 6 and if its in a nuget package its no more difficult than adding in the .csproj
> 
> ```
> <TargetFramework>netcoreapp3.1</TargetFramework>
> <TargetFrameworks>netcoreapp3.1;net5.0;net6.0</TargetFrameworks>
> ```

This is plain stupid

**Comment by IrishBruse** [comment]
Care to elaborate? Its what I have been doing for my packages on NuGet.

**Comment by BlackOfWorld** [comment]
> Care to elaborate? Its what I have been doing for my packages on NuGet.
Oh sorry, I didn't notice the .net core 3, your library is fine. That's what most people do anyways, but I'd recommend switching to .net standard.

Before I noticed:
NuGet downloads entire package, including .net 5 and .net 6. 
.Net standard is available everywhere, and downloading it for .net 5 and .net 6 is just wasting space without any benefits. It's not saving performance, nor the output binary file

**Comment by IrishBruse** [comment]
I use `system.text.json` so i cant but yeah usually best to use .net standard when possible

**Comment by tom-weiland** [comment]
I've put making it a nuget package on my todo list, so I'll look into it at some point.

**Comment by ArcadeArchie** [comment]
@tom-weiland when you get to it, you might wanna have a look at Github Actions to automate the build and release steps

**Comment by ERmilburn02** [comment]
> I've put making it a nuget package on my todo list, so I'll look into it at some point.

Any updates on this?

**Comment by tom-weiland** [comment]
There is now (finally) a [nuget package](https://www.nuget.org/packages/RiptideNetworking.Riptide)!

Ignore the fact that I didn't realize that the nuget site doesn't support inline HTML in their markdown and that I can't update it until the next version 😅
