### ISSUE TITLE
dose it work on sanctioned countrys 

### ISSUE THREAD

**Issue by mostafablender** [RiptideNetworking/Riptide#120]
hi i want to know if it work in iran and other countrys that are in usa sanction ?

**Comment by tom-weiland** [comment]
Some brief research on the topic seems to indicate that US sanctions on Iran don't affect Iranian citizens' access to the internet, at least not in a restrictive way. As far as I can tell, Iran's own government surveils and censors its citizens' telecommunications & internet access in an attempt to restrict access to certain information, while US internet-related sanctions aim to prevent the Iranian government from being able to do so.

As such, I think the actual question here is *does Riptide work in countries whose governments restrict their citizens' access to the internet?* The answer is that I don't know, as I'm not familiar with exactly what kind of internet restrictions governments like Iran and China have implemented.

The only way to know for sure is to try it, but if you end up using Riptide for something which the Iranian government doesn't like, you might find it no longer working at some point :P
