### ISSUE TITLE
Client _._._._:_ stopped responding while the connection was fully established!

### ISSUE THREAD

**Issue by minhtribui153** [RiptideNetworking/Riptide#125]
![image](https://github.com/RiptideNetworking/Riptide/assets/78627269/baad937f-46fe-4513-bbe0-bbb1a0c8a7d9)
![image](https://github.com/RiptideNetworking/Riptide/assets/78627269/75e1bd4c-42f8-4fe5-9e73-4c7930bbadf4)

The client side could not connect properly when on the Unity Editor, but when the client and server side was built, there seem to be no error on both sides.

What I expected: Both the client side and the server side should connect without delay since they are both on a local machine when I started pressing the Play Mode button.

How to reproduce: Create a `NetworkManager` instance for the client and the server and make them connect to each other.

I'm not sure if this is a Unity issue, but it seems that ever since Unity 2023 was released, these connection problems seem to occur on the Unity Editor on all versions of Riptide.

**Comment by tom-weiland** [comment]
What version of Riptide are you using?

**Comment by minhtribui153** [comment]
I'm currently using Riptide v2.1.2. I've tried using v2.0.0, but it also has the same error.

**Comment by tom-weiland** [comment]
Do you have the Run in Background setting enabled in both projects?

**Comment by minhtribui153** [comment]
Thanks a lot, it actually worked!
![image](https://github.com/RiptideNetworking/Riptide/assets/78627269/42ae2e82-e1e2-4150-95e4-69d1103ef90d)
![image](https://github.com/RiptideNetworking/Riptide/assets/78627269/83fc1e81-cc2c-4be1-8ec8-259a1dd12e8e)
