### ISSUE TITLE
Change Id method

### ISSUE THREAD

**Issue by Per6** [RiptideNetworking/Riptide#136]
Can a ChangeId(ushort id) function be implemented for messages? i would use that for messages, that a server just needs to resend to somewhere else.

**Comment by tom-weiland** [comment]
What ID would this `ChangeID` method change? Are you talking about a message to which you've written a client's ID via `AddUShort`, and now you want to send that same message again with the same data except for the ID value?

You can use the `SetBits` method to overwrite a range of bit starting at a given bit, which should do what you want (if I've understood correctly).

**Comment by Per6** [comment]
yes, you've understood correctly. While trying to program that i learned, i can just resend it with the same id and it'll go to the client because it was sent from the server.
