### ISSUE TITLE
Not supported on .NET Framework 3.5

### ISSUE THREAD

**Issue by NetheriteOfficial** [RiptideNetworking/Riptide#154]
.NET Standard isn't supported in Doorstop 3-something and Unity 5.0.0 doesn't support doorstop 4.3.0 that supports net 8.0. I cannot upgrade engine version because its a modification

**Comment by tom-weiland** [comment]
I don't know what Doorstop 3 is, but Riptide is built for Unity 2019.4 and beyond (as indicated by the Unity [package.json](https://github.com/RiptideNetworking/Riptide/blob/unity-package/Packages/Core/package.json#L6)). If you want to fork the repo and make it work for Unity 5/.NET Framework 3.5 you are of course free to do so, but this is not a change I want to make to this core/official repo.

**Comment by NetheriteOfficial** [comment]
Doorstop in Unity is a C# Loader that loads C# code outside of unity faster than the engine itself, so you can add additional code to the game with the usage of Harmony. Doorstop was used in universal mod loaders like BepInEx or in proprietary mod loaders like BSIPA or MSCLoader

**Comment by NetheriteOfficial** [comment]
Also i did a recompile to .NET Framework 3.5 but windows native function for reserving sockets always throws an exception that a pointer is wrong
