### ISSUE TITLE
Server not listening?

### ISSUE THREAD

**Issue by AlaskanDruid** [RiptideNetworking/Riptide#161]
I may be feeling kind of stupid right now, but I cannot find a github discussions tab for this project :/ Anyhow, I made a sample program. Normally, I would put this as a new discussion in the discussion tab to brainstorm with the community to confirm its a bug/issue before reporting it as such :( 

As a C# console app (no unity), the below code will not accept any connections at all. This is as barebones as I can make it. Tried connecting with various clients via 127.0.0.1 (port 7778) no go for that port nor any other ports. Just keep getting connection refused. Firewall is completely off (on Windows 11).  I am starting to think maybe the newest windows 11 patch disabled udp (again, this happened before in a 2022 patch). However, I wanted to double check ...

(I should mention the firewall is completely turned off)

```


using Riptide;
using Riptide.Utils;

namespace ServerServer
{
    internal class Program
    {
        static void Main(string[] args)
        {
            RiptideLogger.Initialize(Console.WriteLine, true);

            var server = new Server();

            server.ConnectionFailed += Server_ConnectionFailed;
            server.ClientConnected += Server_ClientConnected;
            server.ClientDisconnected += Server_ClientDisconnected;

            server.Start(7778, 100);

            Console.WriteLine("Press ESC to shutdown.");
            Console.WriteLine("");

            do
            {

                server.Update();


                while (!Console.KeyAvailable)
                {
                    Thread.Sleep(1);
                }
            } while (Console.ReadKey(true).Key != ConsoleKey.Escape);

            server.Stop();

            server.ClientConnected -= Server_ClientConnected;
            server.ClientDisconnected -= Server_ClientDisconnected;
            server.ConnectionFailed -= Server_ConnectionFailed;

        }

        private static void Server_ClientDisconnected(object? sender, ServerDisconnectedEventArgs e)
        {
            throw new NotImplementedException();
        }

        private static void Server_ClientConnected(object? sender, ServerConnectedEventArgs e)
        {
            throw new NotImplementedException();
        }

        private static void Server_ConnectionFailed(object? sender, ServerConnectionFailedEventArgs e)
        {
            throw new NotImplementedException();
        }

    }
}

```

**Comment by AlaskanDruid** [comment]
Huh, was thinking my brain was fried last night, however, even with the changes above, same issue, server keeps refusing connection. Im starting to think it is another udp blocking win11 patch. ugh. Thanks anyhow, looks like I need to look at the OS level :/

**Comment by CrossV4** [comment]
i didnt think it is about from win11. I am using win11 and my all servers runs as expected. As i see you throwing an exception for not written code yet.

`private static void Server_ConnectionFailed(object? sender, ServerConnectionFailedEventArgs e)
        {
            throw new NotImplementedException();
        }`
 
 so when a client try to connect your server gets an exception and it can maybe terminate the whole thread. So remove `throw new NotImplementedException();` then re-try.

**Comment by AlaskanDruid** [comment]
Unfortunately, that isn't it. What version/patch level of Windows 11 do you have? I have ..

Version 23H2 (OS Build: 22631.4460)

I'm still hunting down patches.

````

using Riptide;
using Riptide.Utils;

namespace ServerServer
{
    internal class Program
    {
        static void Main(string[] args)
        {
            RiptideLogger.Initialize(Console.WriteLine, true);

            var server = new Server();

            server.ConnectionFailed += Server_ConnectionFailed;
            server.ClientConnected += Server_ClientConnected;
            server.ClientDisconnected += Server_ClientDisconnected;

            server.Start(7778, 100);

            Console.WriteLine("Press ESC to shutdown.");
            Console.WriteLine("");

            do
            {
                server.Update();
                Thread.Sleep(10);

            } while (Console.ReadKey(true).Key != ConsoleKey.Escape);

            server.Stop();

            server.ClientConnected -= Server_ClientConnected;
            server.ClientDisconnected -= Server_ClientDisconnected;
            server.ConnectionFailed -= Server_ConnectionFailed;

        }

        private static void Server_ClientDisconnected(object? sender, ServerDisconnectedEventArgs e)
        {
            Console.WriteLine("Server_ClientDisconnected");
        }

        private static void Server_ClientConnected(object? sender, ServerConnectedEventArgs e)
        {
            Console.WriteLine("Server_ClientConnected");
        }

        private static void Server_ConnectionFailed(object? sender, ServerConnectionFailedEventArgs e)
        {
            Console.WriteLine("Server_ConnectionFailed");
        }

    }
}

````

**Comment by CrossV4** [comment]
hmm, no you still getting wrong idea. As i said in my first reply, your loop block `server.Update();` is runs just one time. I tested your `while (Console.ReadKey(true).Key != ConsoleKey.Escape);` condition, and i see that your condition never return false or true until user give an input value. So thats way your while block cannot run `server.Update();` block.

So you should use a dynamic boolean value instead of thread input functions. I.e `bool isrunning = true; while(isrunning)`.

Then check the users input from another thread because a thread is responsible from running this your while loop. So create a thread, and put this while loop into it and in Main thread check and get users input or do whatever you want.

If you cant manage it to do [check this demo from riptide api owner](https://github.com/RiptideNetworking/Riptide/blob/main/Demos/Console/ConsoleServer/Program.cs)

**Comment by tom-weiland** [comment]
As mentioned by others, `Console.ReadKey()` is a blocking call and will prevent the thread from continuing execution, which means you effectively aren't calling `server.Update()`. The demo that @CrossV4 linked is mostly for conducting tests so it is not very polished but it does show how to get Riptide working in a console app.
