### ISSUE TITLE
Allow servers to specify which IP Address they should listen to

### ISSUE THREAD

**Issue by evilfactory** [RiptideNetworking/Riptide#26]
Currently the IP Address that the server listens to is hard coded to `IPAddress.IPv6Any`, it would be nice if you could specify the IP Address when calling `Server.Start`

**Comment by tom-weiland** [comment]
The server shouldn't be specifying an IP to listen on though...

`IPAddress.IPv6Any` [tells the socket to listen on all network interfaces](https://docs.microsoft.com/en-us/dotnet/api/system.net.ipaddress.ipv6any).

**Comment by evilfactory** [comment]
Yes, but in more advanced network setups, you sometimes don't want the server to listen to all your IPs:

1) Multiple server instances running on the same machine, with the same port.
2) Reverse proxies, it doesn't make sense for the server to listen to all IPs, you want your server to be behind the proxy, not along side with it.
3) Security, sometimes you don't want the server to be accessible on the public network, so you set the server to listen to localhost instead.

**Comment by MasterMann** [comment]
@tom-weiland if the server runs on a system with multiple networks/NICs, there may be a need to restrict listening only to a specific network, for example for security reasons

**Comment by tom-weiland** [comment]
For someone who has built a networking solution like this, I'm probably a lot less familiar with "advanced network setups" than I should be, so I'm genuinely asking for clarification here @evilfactory.

> Multiple server instances running on the same machine, with the same port.

If you're running multiple servers on the same machine, wouldn't it be better to just use a different port? Or is the argument here that you may have a service already listening on the public IP, and you want to listen on the same port and only need localhost connections (or vice versa)? That definitely seems like quite the edge case, but maybe it's more common than I think...?

> Reverse proxies, it doesn't make sense for the server to listen to all IPs, you want your server to be behind the proxy, not along side with it.

This might be where my ignorance is showing, but couldn't you just not forward the port to avoid publicly exposing the server?

> Security, sometimes you don't want the server to be accessible on the public network, so you set the server to listen to localhost instead.

Again, just not forwarding the port in question would solve the problem, no?

I'm not opposed to adding some kind of way to set which network interfaces are listened on, just wondering how necessary it actually is.
