### ISSUE TITLE
Received sequence IDs gap printed to console with a smooth connection.

### ISSUE THREAD

**Issue by Tornadoally** [RiptideNetworking/Riptide#41]
"The gap between received sequence IDs was very large" continuously printed to console, even after connection returns to a smooth state. This occurred when I was running a Riptide Client and server on my computer and saved a file in another application which took my computer's resources. The expected result would be to stop printing this and correct the sequence IDs.

**Comment by tom-weiland** [comment]
Were you ever able to reproduce this? Is it still an issue? I'd be especially curious if it still happens with #109 as that made a lot of changes to how the whole sequence ID system works.

**Comment by Tornadoally** [comment]
The issue persists in v2.0 but is fixed in the dev package. Thanks!
