### ISSUE TITLE
LanDiscovery.SendBroadcast throws SocketException: Access denied

### ISSUE THREAD

**Issue by marverlous811** [RiptideNetworking/Riptide#45]
I'm using your network library for my game project. Everything is normal when I develop in window. But when I clone a project to MacOS, I have a problem. It threw exception "socket permission denied" in method `SendBoardcast` of class `LanDiscovery`. I think it not have permission for macOS network, although I ran unity as sudo. And I suspect IOS app maybe have this problem.

I'm using MacOS Monterey 12.2.1, and MacBook pro 2021

**Comment by tom-weiland** [comment]
> It threw exception "socket permission denied"

I'll look into it at some point (although it may be a while until I get around to it), but is that the full error message? Whatever other information may be included in the rest of the error could be helpful.

**Comment by marverlous811** [comment]
I have got this bug when build game to android. It maybe relate with this topic 
https://forum.unity.com/threads/solved-unity-android-udpclient-send-access-denied.842239/

And my game in PC cannot found host in android, although they are both found each other when using ping in command line

**Comment by MustachoMan** [comment]
> ```
> SocketException: Access denied
> System.Net.Sockets.Socket.SendTo (System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.Net.Sockets.SocketFlags socketFlags, System.Net.EndPoint remoteEP) (at <171a3352ba4a4b8aaa2993d306570161>:0)
> System.Net.Sockets.Socket.SendTo (System.Byte[] buffer, System.Net.EndPoint remoteEP) (at <171a3352ba4a4b8aaa2993d306570161>:0)
> RiptideNetworking.Utils.LanDiscovery.SendBroadcast () (at <205a6c4887a04d59abb3434ed0f7c989>:0)
> CustomNetwork.RiptideTransporter+<HostScanning>d__11.MoveNext () (at Assets/Scripts/Network/RiptideTransporter.cs:66)
> UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
> ```
> 
> this is full error message I got.

This might be a bit too late, but maybe this will be useful for others.

I don't have a MAC so I can't really test this, but I have a theory that the socket reffers to the CPU.

If you access the RiptideNetworking.dll in your Unity assets you will see some settings and constrictions you can set up, one of them is restricted and allowed devices, which includes an allowed CPU list in the MAC section
![Capture](https://github.com/RiptideNetworking/Riptide/assets/142942110/d197cc11-6e11-4145-8597-6301d8735e8c)
Changing this to "Any CPU" should fix the issue by the looks of it
![image](https://github.com/RiptideNetworking/Riptide/assets/142942110/0226a0ea-e7c2-4432-946b-281be506e8bf)

Something worth looking into

**Comment by bschoun** [comment]
I know this is an old issue, but I got this exact error in OS X. I was able to get rid of it by adding the following to the constructor in LanDiscovery.cs (after initializing `socket`):

`socket.EnableBroadcast = true;`

Hope this helps!

**Comment by tom-weiland** [comment]
Closing this as the `LanDiscovery` class was removed in v2 and would be completely overhauled if it ever makes a return.
