### ISSUE TITLE
After connecting and disconnection the same Client instance a cupple of times it stops working

### ISSUE THREAD

**Issue by MarcellVokk** [RiptideNetworking/Riptide#60]
Okay, so I have a `Cleint client = new Client()` and after connecting and disconnecting it for 5 (at least for me it was 5) times, the Client get's bugged and the riptide logger prints this `[18:54:32] (CLIENT): Connection to server failed!` and `[18:54:32] (CLIENT): Connecting to 127.0.0.1:9564...` (in this order...), and if I try again, it does the same thing. The server does not receive any packets... You should look into this because it's realy annoying. For now I have to create new instances each time the client connects to a new server. Everything else is working amazingly though :).

**Comment by tom-weiland** [comment]
Is this happening in a custom project? If so, can you reproduce it in the [dedicated server demo](https://github.com/tom-weiland/RiptideNetworking/tree/main/Demos/Unity/DedicatedServerDemo)?

So it happens on the 6th connection attempt? Every time, or does it vary (or maybe even sometimes not happen at all)?

**Comment by tom-weiland** [comment]
Closing this as I can't reproduce it and there's been no response for over a year. @MarcellVokk let me know if you can provide steps to reproduce the issue in one of the demos, and we can reopen this.
