### ISSUE TITLE
"NullReferenceException" before the first connection attempt.

### ISSUE THREAD

**Issue by corthax** [RiptideNetworking/Riptide#75]
With or without server, before the first connection attempt console is spammed with errors. After - it's ok. 

After clients are connected everything seems to work fine...

Custom project (based on your youtube tutorial).

All breaking code changes are applied.
Installed with Package Manager.

On client, without server:
![2022-10-24 18_31_50-Game](https://user-images.githubusercontent.com/36992223/197567040-1f634f28-9cae-4cd5-ae49-85e5b18497a9.png)

On client, with server:
![2022-10-24 18_33_05-Game](https://user-images.githubusercontent.com/36992223/197567436-6e4089d9-f663-4f0e-9b47-24e7ddb4b757.png)

On server, throw error after client connects, for each client:
![2022-10-24 18_46_45-Window](https://user-images.githubusercontent.com/36992223/197569475-7b9f199b-bf9b-48d8-b32d-e969dbe56bbc.png)

**Comment by tom-weiland** [comment]
The only thing that could cause a NullReferenceException on [line 297 of the Client class](https://github.com/RiptideNetworking/Riptide/blob/unity-package/Packages/Core/Runtime/Core/Client.cs#L297) is `connection` being null, which it will be if you haven't initiated a connection yet. However, Riptide itself does not try to send any messages before initiating a connection, which means that *you* must be trying to send something before connecting...

Do you send messages in `Update` or from anywhere else which might execute before you call your client's `Connect` method?

**Comment by corthax** [comment]
Oh well. Indeed I send messages on Update before client is connected. Previous RiptideNetworking version was ok with that :D
Connection null check with some error message would be nice though, for debugging.

**Comment by tom-weiland** [comment]
> Previous RiptideNetworking version was ok with that

I'm pretty sure it just silently discarded the message though. It wouldn't have tried to actually send it without being connected.

> Connection null check with some error message would be nice though

I mean you *are* getting an error message (the NullReferenceException), and the stack trace should show you exactly what your own code is calling to cause it—it's just that it doesn't explicitly tell you "you can't send messages until you're connected."
