### ISSUE TITLE
More Network Metrics

### ISSUE THREAD

**Issue by xzippyzachx** [RiptideNetworking/Riptide#77]
Ability to get a clients **throughput** and **goodput** with the server. This would help when debugging issues that might be related to bandwidth.
Also maybe the servers overall  **throughput** and **goodput** of all the clients added up.

**Comment by tom-weiland** [comment]
> Ability to get a clients throughput and goodput with the server.

@xzippyzachx what is the difference between throughput and goodput in this case?

**Comment by xzippyzachx** [comment]
> > Ability to get a clients throughput and goodput with the server.
> 
> @xzippyzachx what is the difference between throughput and goodput in this case?

Throughput would be the entire packet including header data and payload data. Goodput is only the useful data so only the actual payload data of the packet.

**Comment by tom-weiland** [comment]
When you say "header data" do you mean Riptide's header or also the protocol/transport header? For the UDP & TCP transports I think that would vary depending on whether you're using IPv4 or IPv6, but I've got no idea what kind of header Steam's networking has 🤔

**Comment by xzippyzachx** [comment]
The correct throughput value would be everything including the protocol/transport headers yeah. Goodput is probably good enough for a built in solution but maybe mention that its the goodput in the XML comments.
