### ISSUE TITLE
Message only contains 62032 unread bytes, which is not enough to retrieve 127568 bytes

### ISSUE THREAD

**Issue by PoligamerYT** [RiptideNetworking/Riptide#85]
Hello, I had this problem when I send a huge amount of data, I know Riptide is not made to send huge data but is there a solution for this?

Here is where I received the data, the problem is that I received only a part of it.

        [MessageHandler(2)]
        public static void ReciveDirectoryC(Message message)
        {
            int dataLenght = message.GetInt();

            string str = Encoding.ASCII.GetString(message.GetBytes(dataLenght));

            Console.WriteLine(str);

            TreeviewPersist.FromJson(str, TreeView);
        }

And here is where I send the data.

        [MessageHandler(1)]
        public static void SendDirecotyrC(ushort id, Message message)
        {
            Message message1 = Message.Create(MessageSendMode.Reliable, 2);

            TreeView treeView = new TreeView();

            ListDirectory(treeView, "C:\\Users\\idk\\Downloads");

            string json = TreeviewPersist.ToJson(treeView);
            byte[] data = Encoding.UTF8.GetBytes(json);

            message1.AddInt(data.Length);
            message1.AddBytes(data, false);

            server.SendToAll(message1);

            Console.WriteLine(json);
        }

Also, I change the `MaxSize` int in the Message class. pls help me

**Comment by tom-weiland** [comment]
One possible cause could be the fact that you're using UTF-8 to convert the string to bytes, but you're using ASCII to convert the bytes back to a string.

If fixing that doesn't solve your problem, print out how many bytes you're sending and the value of the length int that you receive to see if they match.

Also for future reference, the Discord server is usually a better place to get help with troubleshooting your code—GitHub issues are intended for issues related to actual bugs with Riptide.
