### ISSUE TITLE
ios device as clients cannot connect a PC as server 

### ISSUE THREAD

**Issue by lck666666** [RiptideNetworking/Riptide#88]
I firstly run your Unity Demo Client on Macbook and Demo Server on a windows PC, it works very well.
Then I build the client project on iPhone12, it cannot connect to the PC server though they can PING each other. The log of the iPhone12 on Xcode is Socketexception:  No route to host at System.Net.
What do you think the reason is?

**Comment by lck666666** [comment]
the iOS version is 16.0.2

**Comment by lck666666** [comment]
We think it's the system version of iOS, we tested again on iPhone 14 with system version 16.2 and Samsung's Android devices, and both worked. Sorry to bother you

**Comment by tom-weiland** [comment]
If you find out anything further, let me know!
