### ISSUE TITLE
Not ticking/Updating while not focused

### ISSUE THREAD

**Issue by CrossV4** [RiptideNetworking/Riptide#93]
Server.Update or Client.Update functions don't running while app is not focused. Then clients are disconnecting from server fo reason of afk.

I have put my Client.Update in FixedUpdate void but when i go out of unity editor it doesn't work. Also i have put some ads in my game. When rewarded or interstitial ads showing Client.Update doesn't work either. When players watching some ads connection being corrupted. Also when game focusses changes connection corrupting so what i am mean, When player needs to write something when keyboard appears system focus has changing to keyboard so then Client.Update doesn't run that's way connection being destroyed.

How do i handle run that Client.Update while application lifespan is alive ?

**Comment by tom-weiland** [comment]
> Server.Update or Client.Update functions don't running while app is not focused.

You need to enable the Run in Background setting in your project(s).

> When players watching some ads connection being corrupted.

If enabling Run in Background doesn't solve this, you may have to set the client's `CanTimeout` property to false (on both ends or it won't work) while they watch an ad, or you can increase the `TimeoutTime` (again, on both ends).
