### ISSUE TITLE
Feature request | Packet Flooding Countermeasures

### ISSUE THREAD

**Issue by megalithos** [RiptideNetworking/Riptide#95]
I am thinking of adding a feature to auto kick/timeout/ipban client/ip when a client sends too many packets.

Basically anti packet flood.

Why? With current system there is no such checks in place (correct me if I'm wrong) so you can easily DoS the whole server by just flooding packets. I think even just changing the timescale with tool like cheat engine could cause significant DoS.

What do you guys think?

**Comment by tom-weiland** [comment]
As I mentioned on Discord, many server hosting providers offer DoS protection, and as such I'm not sure that that's necessarily something that Riptide needs to deal with, though I can't say I'm particularly well informed on this topic and where that responsibility ought to lie.

Your point about hosting providers' DoS protection likely being aimed at larger scale attacks is also valid, so I'm not ruling this out—just wanted to add the context.

**Comment by tom-weiland** [comment]
I recently added bandwidth-related metrics to connections (4d9f259019a818ea363319e4955457b795aa7eb0) which includes the number of messages which are being sent/received. With these metrics it becomes really easy for devs to implement their own checks for packet flooding.

I think leaving this up to devs to implement themselves is a better approach than trying to implement a one-size-fits-all packet flooding detection/countermeasure system into the library itself. This way there's more flexibility for those that need such a system and they can decide for them and their project what exactly constitutes "packet flooding", and for those that don't need something like this there is no extra (pointless) overhead.
