### ISSUE TITLE
Timeout Time For Individual Connections

### ISSUE THREAD

**Issue by xzippyzachx** [RiptideNetworking/Riptide#97]
Currently we have the ability to set the timeout time from the server for all clients `Server.TimeoutTime` and the timeout time from the client `Client.TimeoutTime`. It would be nice to have the ability to get/set the timeout time of individual connections from the server.

**Comment by tom-weiland** [comment]
Commit 7b72dd6f9820f15282bbbeb95afae23cc4df69cb makes this possible.
